- name: select the hosts 
  hosts: apache
  become: yes

  tasks:
    - name: install the apache
      yum: 
        name: httpd
        state: latest

    - name: start the apache
      service:
        name: httpd
        state: started
            
